apiVersion: v1
kind: ConfigMap
metadata:
  name: instance-metric-initdb-config
  namespace: management-controller
data:
  initdb.sh: |
    #!/bin/sh
    influx -execute 'CREATE DATABASE opencsd_instance_metric_db' \
    && influx -execute 'CREATE RETENTION POLICY "day_policy" ON "opencsd_instance_metric_db" DURATION 7d REPLICATION 1 DEFAULT'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: management-controller
data:
  my.cnf: |
    [mysqld]
    port=40806
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: instance-metric-collector
  namespace: management-controller
spec:
  selector:
    matchLabels:
      app: instance-metric-collector
  template:
    metadata:
      labels:
        app: instance-metric-collector
    spec:
      nodeSelector:
        layer: operation
      serviceAccountName: instance-metric-collector
      imagePullSecrets:
        - name: regcred
      hostNetwork: true
      containers:
        - name: influxdb
          image: influxdb:1.7
          ports:
            - containerPort: 8086 
          env:
            - name: INFLUXDB_DB
              value: opencsd_instance_metric_db
            - name: INFLUXDB_PASSWORD
              value: ketilinux
            - name: INFLUXDB_USER
              value: keti
          volumeMounts:
            - name: influxdb-storage
              mountPath: /var/lib/influxdb
            - name: instance-metric-db-entrypoint
              mountPath: /docker-entrypoint-initdb.d
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m" 
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 40806
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ketilinux
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: mysql-config
              mountPath: /etc/mysql/my.cnf
              subPath: my.cnf
            - name: instance-info-basedb-config
              mountPath: /etc/config/base.sql
              subPath: base.sql
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
        - name: instance-metric-collector
          image: ketidevit2/instance-metric-collector:v1.0
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: INFLUXDB_DB
              value: opencsd_instance_metric_db
            - name: INFLUXDB_PASSWORD
              value: ketilinux
            - name: INFLUXDB_USER
              value: keti
            - name: INFLUXDB_PORT
              value: "8086"
            - name: MYSQL_ROOT_PASSWORD
              value: ketilinux
            - name: MYSQL_PORT
              value: "40806"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: host-proc
              mountPath: /host/proc
              readOnly: true
            - name: host-sys
              mountPath: /host/sys
              readOnly: true
            - name: host-rootfs
              mountPath: /rootfs
              readOnly: true
            - name: instance-info-basedb-config
              mountPath: /etc/config/base.sql
              subPath: base.sql
      volumes:
        - name: host-proc
          hostPath:
            path: /proc
        - name: host-sys
          hostPath:
            path: /sys
        - name: host-rootfs
          hostPath:
            path: /
        - name: influxdb-storage
          hostPath:
            path: /mnt/instance_metric_influxdb
        - name: mysql-storage
          hostPath:
            path: /mnt/instance_info_mysql
        - name: instance-metric-db-entrypoint
          configMap:
            name: instance-metric-initdb-config
            defaultMode: 0755
        - name: mysql-config
          configMap:
            name: mysql-config
        - name: instance-info-basedb-config
          configMap:
            name: instance-info-basedb-config
      tolerations:
        - key: "use"
          operator: "Equal"
          value: "no"
          effect: "NoSchedule"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: instance-metric-collector
  namespace: management-controller
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: instance-metric-collector
subjects:
- kind: ServiceAccount
  name: instance-metric-collector
  namespace: management-controller
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io