apiVersion: v1
kind: Service
metadata:
  name: instance-metric-collector-svc
  namespace: management-controller
  labels:
    name: instance-metric-collector
    namespace: management-controller
spec:
  ports:
    - port: 40804
      targetPort: 40804
      protocol: TCP
  selector:
    app: instance-metric-collector
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: instance-metric-collector-influxdb-svc
#   namespace: management-controller
#   labels:
#     name: instance-metric-collector
#     namespace: management-controller
# spec:
#   ports:
#     - port: 8086
#       targetPort: 8086
#       protocol: TCP
#   selector:
#     app: instance-metric-collector
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: instance-metric-collector-mysql-svc
#   namespace: management-controller
#   labels:
#     name: instance-metric-collector
#     namespace: management-controller
# spec:
#   ports:
#     - port: 40806
#       targetPort: 8086
#       protocol: TCP
#   selector:
#     app: instance-metric-collector