apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencsd-volume-allocator
  namespace: management-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: opencsd-volume-allocator
      namespace: management-controller
  template:
    metadata:
      labels:
        name: opencsd-volume-allocator
        namespace: management-controller
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: opencsd-volume-allocator
          image: ketidevit2/opencsd-volume-allocator:v0.0.1
          imagePullPolicy: Always
      nodeSelector:
        key: master
