apiVersion: v1
kind: Service
metadata:
  name: opencsd-engine-deployer
  namespace: management-controller
  labels:
    name: opencsd-engine-deployer
    namespace: management-controller
spec:
  type: NodePort
  ports:
    - port: 40804
      targetPort: 40804
      nodePort: 30804
      protocol: TCP
  selector:
    name: opencsd-engine-deployer
    namespace: management-controller
