apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencsd-controller
  namespace: management-controller
  labels:
    app: opencsd-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencsd-controller
  template:
    metadata:
      labels:
        app: opencsd-controller
      name: opencsd-controller
    spec:
      serviceAccountName: opencsd-controller
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        key: master
      containers:
        - name: opencsd-controller
          image: ketidevit2/opencsd-controller:v1.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"    
            limits:
              memory: "1Gi" 
              cpu: "1"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ketilinux
            - name: MYSQL_USER
              value: keti
            - name: MYSQL_PASSWORD
              value: ketilinux
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opencsd-controller
  namespace: management-controller
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opencsd-controller-crb
subjects:
- kind: ServiceAccount
  name: opencsd-controller
  namespace: management-controller
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io