apiVersion: v1
kind: Service
metadata:
  name: opencsd-instance-manager
  namespace: management-controller
  labels:
    name: opencsd-instance-manager
    namespace: management-controller
spec:
  type: NodePort
  ports:
    - port: 40805
      targetPort: 40805
      nodePort: 30805
      protocol: TCP
  selector:
    name: opencsd-instance-manager
    namespace: management-controller
