apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencsd-api-server
  namespace: management-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: opencsd-api-server
      namespace: management-controller
  template:
    metadata:
      labels:
        name: opencsd-api-server
        namespace: management-controller
    spec:
      serviceAccountName: opencsd-api-server
      imagePullSecrets:
        - name: regcred
      containers:
        - name: opencsd-api-server
          image: ketidevit2/opencsd-api-server:v1.0
          imagePullPolicy: Always
          env:
            - name: INFLUXDB_DB
              value: opencsd_instance_metric_db
            - name: INFLUXDB_PASSWORD
              value: ketilinux
            - name: INFLUXDB_USER
              value: keti
            - name: INFLUXDB_PORT
              value: "8086"
            - name: MYSQL_ROOT_PASSWORD
              value: ketilinux
            - name: MYSQL_PORT
              value: "40806"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
                requests:
                  memory: "128Mi"
                  cpu: "250m"    
                limits:
                  memory: "1Gi" 
                  cpu: "1"
      nodeSelector:
        key: master
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opencsd-api-server
  namespace: management-controller
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opencsd-api-server-crb
subjects:
- kind: ServiceAccount
  name: opencsd-api-server
  namespace: management-controller
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
