apiVersion: v1
kind: Service
metadata:
  name: opencsd-api-server-svc
  namespace: management-controller
  labels:
    name: opencsd-api-server
    namespace: management-controller
spec:
  type: NodePort
  ports:
    - port: 40800
      targetPort: 40800
      nodePort: 30800
      protocol: TCP
  selector:
    name: opencsd-api-server
    namespace: management-controller
